### ISSUE TITLE
Micro receiver question

### ISSUE THREAD

**Issue by stanekTM** [TheDIYGuy999/Micro_RC_Receiver#10]
I want to thank you in advance for this amazing project.
This is exactly what I am looking for for my racing micro cars.
I will replace the original PCBs with new ones so that I can use the pistol transmitter from the OpenAVRc project.
Did I understand that the protocol is not compatible with any of the Multiprotokol projects ?
So I'll have to transfer the protocol.
Is there a project version NRF24L .. with its own RFU + MCU with motor driver control and servo channel output without additional processor ?
Thanks in advance for the inspiration.
George

**Comment by TheDIYGuy999** [comment]
Thank you. Yes, the protocol is not compatible. Think it's not possible to control motor driver or servos without an additional MCU. Let me know, if you are able to transfer the protocol.
