### ISSUE TITLE
B36

### ISSUE THREAD

**Issue by Ahmedabdulamir** [TheDIYGuy999/Micro_RC_Receiver#9]
Hello again,

I see that you are using this receiver for the B36 WPL, I was wondering if you used the integrated receiver or just used an external ESC?. Im planning to use a Mini pro and a regular ESC as a receiver, but I feel hard to understand the change in the wiring diagram you posted. for the regular ESC you only supply PWD input. shall I connect only D3 to ESC?. 

Thanks

**Comment by TheDIYGuy999** [comment]
Just connect your ESC to the 3 pin servo connector CH3. In case you of a Pro Mini, connect it to Pin A2. Of course you have to connect GND and RAW as well
